#!/usr/bin/env bash
# Same as 4, displays "I am invincible!!!" when receiving SIGTERM signal

while true
do
    echo 'To infinity and beyond'
    sleep 2
    trap 'echo"I am invincible!!!"' SIGTERM
done
