#!/usr/bin/env bash
# This bash script will display Best School 10 times but 9 will be Hi

i=1

while [ $i -le 9 ]
do

    echo 'Best School'
    if [ $i -eq 8 ];
    then
	echo 'Hi'
    fi
    ((i++))
done
	
