#!/usr/bin/env bash
#This script will display 10 loops with eight loops as Best School, the 4th loop being bad luck, and the 8th loop being good luck

i=0
while [ $i -le 9 ]
do
    if [ $i -eq 3 ]
    then
	echo 'bad luck'
    elif [ $i -eq 7 ]
    then
	echo 'good luck'
    else
	echo 'Best School'
    fi
    ((i++))
done
