#!/usr/bin/env bash
# This script will display the numbers 1-20, 4 will show bad luck from China, 9 will show bad luck from Japan, 17 will show bad luck from Italy

i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	echo 'bad luck from China'
	;;
	9)
	echo 'bad luck from Japan'
	;;
	17)
	echo 'bad luck from Italy'
	;;
    esac
    i=$((i + 1))
done
